In [ ]:
import pandas as pd
df=pd.read_csv('/content/AB_NYC_2019.csv')
df

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48890,36484665,Charming one bedroom - newly renovated rowhouse,8232441,Sabrina,Brooklyn,Bedford-Stuyvesant,40.67853,-73.94995,Private room,70,2,0,NaN,NaN,2,9
48891,36485057,Affordable room in Bushwick/East Williamsburg,6570630,Marisol,Brooklyn,Bushwick,40.70184,-73.93317,Private room,40,4,0,NaN,NaN,2,36
48892,36485431,Sunny Studio at Historical Neighborhood,23492952,Ilgar & Aysel,Manhattan,Harlem,40.81475,-73.94867,Entire home/apt,115,10,0,NaN,NaN,1,27
48893,36485609,43rd St. Time Square-cozy single bed,30985759,Taz,Manhattan,Hell's Kitchen,40.75751,-73.99112,Shared room,55,1,0,NaN,NaN,6,2
48894,36487245,Trendy duplex in the very heart of Hell's Kitchen,68119814,Christophe,Manhattan,Hell's Kitchen,40.76404,-73.98933,Private room,90,7,0,NaN,NaN,1,23

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48895 entries, 0 to 48894
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              48895 non-null  int64
 1   name                            48879 non-null  object
 2   host_id                         48895 non-null  int64
 3   host_name                       48874 non-null  object
 4   neighbourhood_group             48895 non-null  object
 5   neighbourhood                   48895 non-null  object
 6   latitude                        48895 non-null  float64
 7   longitude                       48895 non-null  float64
 8   room_type                       48895 non-null  object
 9   price                           48895 non-null  int64
 10  minimum_nights                  48895 non-null  int64
 11  number_of_reviews               48895 non-null  int64
 12  last_review                     38843 non-null  object
 13  reviews_per_month               38843 non-null  float64
 14  calculated_host_listings_count  48895 non-null  int64
 15  availability_365                48895 non-null  int64
dtypes: float64(3), int64(7), object(6)
memory usage: 6.0+ MB

In [ ]:
#Tìm giá trị null
df.isnull().sum()

id                                    0
name                                 16
host_id                               0
host_name                            21
neighbourhood_group                   0
neighbourhood                         0
latitude                              0
longitude                             0
room_type                             0
price                                 0
minimum_nights                        0
number_of_reviews                     0
last_review                       10052
reviews_per_month                 10052
calculated_host_listings_count        0
availability_365                      0
dtype: int64

In [ ]:
#Xóa các giá trị null, bị trùng lập
df=df.dropna()
df = df.drop_duplicates( keep=False)
print(df)

             id                                              name    host_id  \
0          2539                Clean & quiet apt home by the park       2787
1          2595                             Skylit Midtown Castle       2845
3          3831                   Cozy Entire Floor of Brownstone       4869
4          5022  Entire Apt: Spacious Studio/Loft by central park       7192
5          5099         Large Cozy 1 BR Apartment In Midtown East       7322
...         ...                                               ...        ...
48782  36425863        Lovely Privet Bedroom with Privet Restroom   83554966
48790  36427429                          No.2 with queen size bed  257683179
48799  36438336                                   Seas The Moment  211644523
48805  36442252                     1B-1B apartment near by Metro  273841667
48852  36455809           Cozy Private Room in Bushwick, Brooklyn   74162901

         host_name neighbourhood_group    neighbourhood  latitude  longitude  \
0             John            Brooklyn       Kensington  40.64749  -73.97237
1         Jennifer           Manhattan          Midtown  40.75362  -73.98377
3      LisaRoxanne            Brooklyn     Clinton Hill  40.68514  -73.95976
4            Laura           Manhattan      East Harlem  40.79851  -73.94399
5            Chris           Manhattan      Murray Hill  40.74767  -73.97500
...            ...                 ...              ...       ...        ...
48782        Rusaa           Manhattan  Upper East Side  40.78099  -73.95366
48790         H Ai              Queens         Flushing  40.75104  -73.81459
48799          Ben       Staten Island      Great Kills  40.54179  -74.14275
48805       Blaine               Bronx       Mott Haven  40.80787  -73.92400
48852    Christine            Brooklyn         Bushwick  40.69805  -73.92801

             room_type  price  minimum_nights  number_of_reviews last_review  \
0         Private room    149               1                  9  2018-10-19
1      Entire home/apt    225               1                 45  2019-05-21
3      Entire home/apt     89               1                270  2019-07-05
4      Entire home/apt     80              10                  9  2018-11-19
5      Entire home/apt    200               3                 74  2019-06-22
...                ...    ...             ...                ...         ...
48782     Private room    129               1                  1  2019-07-07
48790     Private room     45               1                  1  2019-07-07
48799     Private room    235               1                  1  2019-07-07
48805  Entire home/apt    100               1                  2  2019-07-07
48852     Private room     30               1                  1  2019-07-08

       reviews_per_month  calculated_host_listings_count  availability_365
0                   0.21                               6               365
1                   0.38                               2               355
3                   4.64                               1               194
4                   0.10                               1                 0
5                   0.59                               1               129
...                  ...                             ...               ...
48782               1.00                               1               147
48790               1.00                               6               339
48799               1.00                               1                87
48805               2.00                               1                40
48852               1.00                               1                 1

[38170 rows x 16 columns]

In [ ]:
#Xóa các cột không cần thiết
df = df.drop('calculated_host_listings_count', axis=1)
df.drop(['id', 'last_review'], axis = 1, inplace = True)
print(df)

                                                    name   host_id  \
0                     Clean & quiet apt home by the park      2787
1                                  Skylit Midtown Castle      2845
2                    THE VILLAGE OF HARLEM....NEW YORK !      4632
3                        Cozy Entire Floor of Brownstone      4869
4       Entire Apt: Spacious Studio/Loft by central park      7192
...                                                  ...       ...
48890    Charming one bedroom - newly renovated rowhouse   8232441
48891      Affordable room in Bushwick/East Williamsburg   6570630
48892            Sunny Studio at Historical Neighborhood  23492952
48893               43rd St. Time Square-cozy single bed  30985759
48894  Trendy duplex in the very heart of Hell's Kitchen  68119814

           host_name neighbourhood_group       neighbourhood  latitude  \
0               John            Brooklyn          Kensington  40.64749
1           Jennifer           Manhattan             Midtown  40.75362
2          Elisabeth           Manhattan              Harlem  40.80902
3        LisaRoxanne            Brooklyn        Clinton Hill  40.68514
4              Laura           Manhattan         East Harlem  40.79851
...              ...                 ...                 ...       ...
48890        Sabrina            Brooklyn  Bedford-Stuyvesant  40.67853
48891        Marisol            Brooklyn            Bushwick  40.70184
48892  Ilgar & Aysel           Manhattan              Harlem  40.81475
48893            Taz           Manhattan      Hell's Kitchen  40.75751
48894     Christophe           Manhattan      Hell's Kitchen  40.76404

       longitude        room_type  price  minimum_nights  number_of_reviews  \
0      -73.97237     Private room    149               1                  9
1      -73.98377  Entire home/apt    225               1                 45
2      -73.94190     Private room    150               3                  0
3      -73.95976  Entire home/apt     89               1                270
4      -73.94399  Entire home/apt     80              10                  9
...          ...              ...    ...             ...                ...
48890  -73.94995     Private room     70               2                  0
48891  -73.93317     Private room     40               4                  0
48892  -73.94867  Entire home/apt    115              10                  0
48893  -73.99112      Shared room     55               1                  0
48894  -73.98933     Private room     90               7                  0

       reviews_per_month  availability_365
0                   0.21               365
1                   0.38               355
2                    NaN               365
3                   4.64               194
4                   0.10                 0
...                  ...               ...
48890                NaN                 9
48891                NaN                36
48892                NaN                27
48893                NaN                 2
48894                NaN                23

[48895 rows x 13 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48895 entries, 0 to 48894
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   name                 48879 non-null  object
 1   host_id              48895 non-null  int64
 2   host_name            48874 non-null  object
 3   neighbourhood_group  48895 non-null  object
 4   neighbourhood        48895 non-null  object
 5   latitude             48895 non-null  float64
 6   longitude            48895 non-null  float64
 7   room_type            48895 non-null  object
 8   price                48895 non-null  int64
 9   minimum_nights       48895 non-null  int64
 10  number_of_reviews    48895 non-null  int64
 11  reviews_per_month    38843 non-null  float64
 12  availability_365     48895 non-null  int64
dtypes: float64(3), int64(5), object(5)
memory usage: 4.8+ MB

In [ ]:
#Xuất dữ liệu đã chuẩn hóa
df.to_csv('/content/AB_NYC_2019.csv',
          columns = ['name' ,	'host_id' ,	'host_name' ,	'neighbourhood_group' ,	'neighbourhood' ,	'latitude' ,	'longitude' ,	'room_type' ,	'price' ,	'minimum_nights' ,	'number_of_reviews'
          , 'reviews_per_month' ,	'availability_365' ]
          , sep='\t', index = False)

In [ ]:
df

,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,reviews_per_month,availability_365
0,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,0.21,365
1,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,0.38,355
2,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,365
3,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,4.64,194
4,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,0.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
48890,Charming one bedroom - newly renovated rowhouse,8232441,Sabrina,Brooklyn,Bedford-Stuyvesant,40.67853,-73.94995,Private room,70,2,0,NaN,9
48891,Affordable room in Bushwick/East Williamsburg,6570630,Marisol,Brooklyn,Bushwick,40.70184,-73.93317,Private room,40,4,0,NaN,36
48892,Sunny Studio at Historical Neighborhood,23492952,Ilgar & Aysel,Manhattan,Harlem,40.81475,-73.94867,Entire home/apt,115,10,0,NaN,27
48893,43rd St. Time Square-cozy single bed,30985759,Taz,Manhattan,Hell's Kitchen,40.75751,-73.99112,Shared room,55,1,0,NaN,2
48894,Trendy duplex in the very heart of Hell's Kitchen,68119814,Christophe,Manhattan,Hell's Kitchen,40.76404,-73.98933,Private room,90,7,0,NaN,23